### ISSUE TITLE
Handle JS async rejections

### ISSUE THREAD

**Issue by arichiardi** [jarppe/sieppari#11]
Hi again! As part of my port to cljs I realized what could be an issue..maybe.

It seems like at the moment the `continue` protocol only accepts one callback, which makes sense most of the times, the only issue being `js/Promise` rejection.

One could add another callback for errors but I am not myself convinced it is the right thing to do. It would certainly handle [this kind of situation](https://github.com/metosin/sieppari/pull/10/files#diff-65ec7a562ed567eecae608009df7756eR215) that at the moment trigger an uncaught error warning.

Or maybe it is simply better to let it blow and fail fast.

Thoughts?

**Comment by arichiardi** [comment]
We are using sieppari - the cljs port - and we really are missing this. 

In case of unexpected exception thrown in a promise there is nothing putting the `:error` in the context and what is worse is that node is then printing a terrible warning and not doing anything significant.

One solution to this would be to add a protocol function on the async context.

It cannot work only on `this`, because channel items would already be consumed. So my hunch would be to pass also the last item `a/continue` consumed.

**Comment by arichiardi** [comment]
Thinking more about this it probably does not make sense to touch the protocols.

Some helper around each `AsyncContex` could go a long way.

Need some more hammock time, any input is welcome :smile:

**Comment by nilern** [comment]
The problem seems to be that we don't catch async exceptions like we do sync ones. So when e.g. a rejected promise appears the Sieppari stack and queue get thrown away, the execution stops and you just get the rejected promise. We probably do have to add error handling functionality to the async protocol.
