### ISSUE TITLE
Consolidate build tools

### ISSUE THREAD

**Issue by miikka** [jarppe/sieppari#13]
After merging #10, both deps.edn and Leiningen are used. I think we should pick one.

* If we go with deps.edn, we need to figure out how to run Clojure tests and deploy releases.
* If we go with Leiningen, we need to figure out how to use Figwheel to run tests with it.
* We can also use https://github.com/RickMoynihan/lein-tools-deps to deduplicate information between the two.

**Comment by nilern** [comment]
I would suggest using Leiningen (as the deps.edn was added just for cljs tests) and using [kaocha](https://github.com/lambdaisland/kaocha) for the tests.

**Comment by miikka** [comment]
Sounds good and using Kaocha is an excellent idea.

**Comment by nilern** [comment]
Working on this
