### ISSUE TITLE
Remove automatic support for 3rd party async libs

### ISSUE THREAD

**Issue by ikitommi** [jarppe/sieppari#17]
It takes whopping 4-5sec to load the `sieppari.core` if there are all the async libs on the classpath. Rough load times from async support:

- core.async: 3sec
- manifold: 500ms
- promesa: 100ms

Client-side aot cache on libs would solve this, but might not be solved any time soon: https://clojureverse.org/t/deploying-aot-compiled-libraries/2545/13

Also, don't think it's a default need to want to use multiple async libs in a same app, so instead, the async-support could be explicit, e.g. use has to load the support ns by her/himself.

**Comment by nilern** [comment]
Working on this.
