### ISSUE TITLE
Access to context

### ISSUE THREAD

**Issue by dspiteself** [jarppe/sieppari#28]
We use pedestal in the context of kafka queues. We use the context extensively for storing connections and database names and other configuration. How would we manage that in Sieppari? Would we need to add it to the request? In pedestal we setup a default context once  and then just assoc `:request` for each kafka message.

**Comment by martinklepsch** [comment]
See more discussion around this in #15 — I'm sure if we there were a PR that would help too :)

**Comment by dspiteself** [comment]
resolved by https://github.com/metosin/sieppari/pull/31
