### ISSUE TITLE
Support for ClojureScript

### ISSUE THREAD

**Issue by ikitommi** [jarppe/sieppari#3]

**Comment by arichiardi** [comment]
I could help on this, very interested in the interceptor pattern a-la-reframe :smile:. I have a question: the `AsyncContext` protocol requires an `await` that does not really suits the callback world of JavaScript - it seems blocking. Would it be it a good idea to add something like `call-back` in case of cljs?

Or something, will come up with an example which is maybe better. Just speculation here :smile:

**Comment by ikitommi** [comment]
Hi, and great to hear about your interest!

What if the whole blocking path would be omitted from cljs? e.g. all code from here on: https://github.com/metosin/sieppari/blob/develop/src/sieppari/core.clj#L77-L82, as there is already the non-blockig / callback-version.

**Comment by arichiardi** [comment]
That sounds sensible to me!

**Comment by ikitommi** [comment]
Looking forward to the PR.

**Comment by arichiardi** [comment]
PR #10 is in progress - seeking advice on the tests

**Comment by arichiardi** [comment]
PR #10 has been merged to develop

**Comment by ikitommi** [comment]
shipped in `0.0.0-alpha6`, big thanks! I think we should push a real version out soon.
