### ISSUE TITLE
Support git deps in tools.deps

### ISSUE THREAD

**Issue by den1k** [jarppe/sieppari#32]
Since sieppari has no production dependencies besides clojure so adding a deps.edn enables git deps via tools.deps.

I've done so [here](https://github.com/den1k/sieppari/blob/clojure-deps/deps.edn) and am currently using that branch of sieppari in a project.

Happy to make a PR adding a `deps.edn` if you're okay with it.

**Comment by ikitommi** [comment]
fixed
