### ISSUE TITLE
Seiparri eats AssertionErrors

### ISSUE THREAD

**Issue by robert-stuttaford** [jarppe/sieppari#57]
Which in turn prevents Sentry.io (our exception tracker of choice) to receive and report AssertionErrors.

Here's how we updated our fork to work around it:

https://github.com/CognicianCorp/sieppari/commit/310d76fed45bf2a9cb8f6be8f51a3c2c2eb45919

**Comment by Ramblurr** [comment]
I have encountered this before too. However AFAIK it was an intentional choice to catch Exception rather than Throwable, as per the README.

**Comment by ikitommi** [comment]
Hmm. Catching Exception doesn't catch AssertionErrors. Catching Throwable would catch it.

```clojure
(try
  (throw (AssertionError. "kikka"))
  (catch Exception e))
; =throw=> Execution error (AssertionError)

(try
  (throw (AssertionError. "kikka"))
  (catch Error _))
; => nil
```
