### ISSUE TITLE
Pedestal links in README no longer work

### ISSUE THREAD

**Issue by juszczakn** [jarppe/sieppari#58]
Since a large part of the README's onboarding is offloaded to this link:

> If you are new to interceptors, check the [Pedestal Interceptors documentation](http://pedestal.io/reference/interceptors).

It seems like it should be reworked to provide a more helpful introduction/explanation of the library.

If the Pedestal project isn't actually dead, perhaps it could just link to the new docs, but it still seems to me that the README should include some information about the basic idea, so as not to fall victim to bitrot again in the future.

**Comment by ikitommi** [comment]
fixed
